// AUTO-GENERATED by scripts/generate_sdc_fuzz_cases.py — do not edit.
// Case 020: core179 SDC reproducer: Eigen SimplicialCholesky numeric factorize, N=512 mseed=12345 mode=numeric-only bseed=555 [lsu-store-buffer]
// Trigger: core 179 SDC, same-socket full load + Eigen factorize numeric update
// (report §11.2). Cluster: lsu-store-buffer.
// SPDX-License-Identifier: Apache-2.0
// Copyright 2025 Intel Corporation.

#define SDC_FUZZ_N          512
#define SDC_FUZZ_MSEED      12345u
#define SDC_FUZZ_MODE       1
#define SDC_FUZZ_BSEED      555u
#define SDC_FUZZ_CLUSTER    "lsu-store-buffer"

#include "sdc_fuzz_case_template.h"

// DECLARE_TEST must appear at file scope in the source file (not a header) so
// scripts/generate-short-ids.pl can discover this test id by regex scan.
DECLARE_TEST(sdc_fuzz_020, "core179 SDC reproducer: Eigen SimplicialCholesky numeric factorize, N=512 mseed=12345 mode=numeric-only bseed=555 [lsu-store-buffer]")
    .groups = DECLARE_TEST_GROUPS(&group_math),
    .test_init = sdc_fuzz_init,
    .test_run = sdc_fuzz_run,
    .test_cleanup = sdc_fuzz_cleanup,
    .desired_duration = -1,
    .quality_level = TEST_QUALITY_BETA,
END_DECLARE_TEST
