// AUTO-GENERATED by scripts/generate_sdc_fuzz_cases.py — do not edit.
// Case 010: core179 SDC reproducer: Eigen SimplicialCholesky numeric factorize, N=384 mseed=12345 mode=compute-both bseed=909 [rob-speculation]
// Trigger: core 179 SDC, same-socket full load + Eigen factorize numeric update
// (report §11.2). Cluster: rob-speculation.
// SPDX-License-Identifier: Apache-2.0
// Copyright 2025 Intel Corporation.

#define SDC_FUZZ_N          384
#define SDC_FUZZ_MSEED      12345u
#define SDC_FUZZ_MODE       0
#define SDC_FUZZ_BSEED      909u
#define SDC_FUZZ_CLUSTER    "rob-speculation"

#include "sdc_fuzz_case_template.h"

// DECLARE_TEST must appear at file scope in the source file (not a header) so
// scripts/generate-short-ids.pl can discover this test id by regex scan.
DECLARE_TEST(sdc_fuzz_010, "core179 SDC reproducer: Eigen SimplicialCholesky numeric factorize, N=384 mseed=12345 mode=compute-both bseed=909 [rob-speculation]")
    .groups = DECLARE_TEST_GROUPS(&group_math),
    .test_init = sdc_fuzz_init,
    .test_run = sdc_fuzz_run,
    .test_cleanup = sdc_fuzz_cleanup,
    .desired_duration = -1,
    .quality_level = TEST_QUALITY_BETA,
END_DECLARE_TEST
