#!/usr/bin/env python3
# generate_sdc_fuzz_cases.py — generate the 100 core-179 SDC reproducer test cases.
#
# Each case is a sandstone test (DECLARE_TEST) that links the Eigen machine code
# (SimplicialCholesky::factorize numeric update — the verified trigger sequence)
# and reproduces core 179's SDC under same-socket load. Cases differ along
# dimensions that do NOT break the trigger (report §5/§8/§10.2/§10.3) and are
# clustered by the three suspected OoO-engine leak points (report §11.2):
#   cluster rename -> physical register rename table (long-lived d4 accumulator)
#   cluster rob    -> ROB / speculation state (compute-both, post-symbolic refresh)
#   cluster lsu    -> LSU store buffer (sparsity/indirect writeback pressure)
#
# Deterministic (no randomness): every parameter is derived from the case index,
# so the build is reproducible.
#
# Output (into tests/cpu/arm64/sdc_fuzzing/):
#   case_NNN_<cluster>.cpp    (100 files)
#   cases_index.csv           (case -> {N, mseed, mode, bseed, cluster, desc})
# The meson.build is hand-written (stable), not regenerated, to list the 100 files.
#
# SPDX-License-Identifier: Apache-2.0
# Copyright 2025 Intel Corporation.

import os
import csv

# PORTING NOTE: this script lives at $REPO/scripts/sdc/ (one level deeper than
# the reference tree's $REPO/scripts/), so the repo root needs one extra
# dirname(). Override with SDC_FUZZ_OUT_DIR to generate into a different path.
OUT_DIR = os.environ.get(
    "SDC_FUZZ_OUT_DIR",
    os.path.join(
        os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
        "tests", "cpu", "arm64", "sdc_fuzzing",
    ),
)

NUM_CASES = 100

# Trigger-safe parameter pools (all empirically verified NOT to break the
# trigger — see report). N >= 256 (§10.3 threshold). Two seeds both trigger
# (§5). numeric-only (mode 1) and compute-both (mode 0) both trigger (§10.2).
NS = [256, 384, 512]                       # §10.3: all >=256 trigger, fixed elem[0]
MSEEDS = [12345, 54321, 98765, 11111, 33333, 77777, 13579, 24680, 97531, 86420]
BSEEDS = [777, 888, 999, 111, 222, 333, 444, 555, 666, 121, 232, 343, 454, 565, 676, 787, 898, 909, 1010, 2020]

# Cluster assignment by index: rotate through (rename, rob, lsu) so the 100
# cases spread across the three suspected leak points.
CLUSTERS = [
    ("rename", "register-rename-table", 1),   # mode 1 numeric-only, longest rename hold
    ("rob",    "rob-speculation",       0),    # mode 0 compute-both, post-symbolic refresh
    ("lsu",    "lsu-store-buffer",      1),    # mode 1, sparsity drives store-buffer pressure
]

def case_params(i):
    """Deterministic per-case parameters derived from index i (0..99)."""
    cluster_name, cluster_long, default_mode = CLUSTERS[i % 3]
    # vary N across the pool — longer column loops deepen the suspected state
    N = NS[i % len(NS)]
    mseed = MSEEDS[i % len(MSEEDS)]
    # b seed: orthogonal to matrix seed; rotate independently
    bseed = BSEEDS[(i + 7) % len(BSEEDS)]
    # mode: mostly the cluster default, but inject a minority cross-mode case
    # every 7th case to verify the state-leak signature (§10.2) across clusters
    mode = default_mode
    if i % 7 == 0:
        mode = 0 if default_mode == 1 else 1
    desc = (f"core179 SDC reproducer: Eigen SimplicialCholesky numeric factorize, "
            f"N={N} mseed={mseed} mode={'numeric-only' if mode==1 else 'compute-both'} "
            f"bseed={bseed} [{cluster_long}]")
    return {
        "idx": i,
        "id": f"sdc_fuzz_{i:03d}",
        "id_num": f"{i:03d}",
        "cluster": cluster_name,
        "cluster_long": cluster_long,
        "N": N,
        "mseed": mseed,
        "mode": mode,
        "bseed": bseed,
        "desc": desc,
    }

CASE_TEMPLATE = """\
// AUTO-GENERATED by scripts/generate_sdc_fuzz_cases.py — do not edit.
// Case {idx:03d}: {desc}
// Trigger: core 179 SDC, same-socket full load + Eigen factorize numeric update
// (report §11.2). Cluster: {cluster_long}.
// SPDX-License-Identifier: Apache-2.0
// Copyright 2025 Intel Corporation.

#define SDC_FUZZ_N          {N}
#define SDC_FUZZ_MSEED      {mseed}u
#define SDC_FUZZ_MODE       {mode}
#define SDC_FUZZ_BSEED      {bseed}u
#define SDC_FUZZ_CLUSTER    "{cluster_long}"

#include "sdc_fuzz_case_template.h"

// DECLARE_TEST must appear at file scope in the source file (not a header) so
// scripts/generate-short-ids.pl can discover this test id by regex scan.
DECLARE_TEST({id}, "{desc}")
    .groups = DECLARE_TEST_GROUPS(&group_math),
    .test_init = sdc_fuzz_init,
    .test_run = sdc_fuzz_run,
    .test_cleanup = sdc_fuzz_cleanup,
    .desired_duration = -1,
    .quality_level = TEST_QUALITY_BETA,
END_DECLARE_TEST
"""

def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    rows = []
    for i in range(NUM_CASES):
        p = case_params(i)
        fname = f"case_{p['id_num']}_{p['cluster']}.cpp"
        with open(os.path.join(OUT_DIR, fname), "w") as f:
            f.write(CASE_TEMPLATE.format(**p))
        rows.append({
            "case_id": p["id"], "file": fname, "N": p["N"],
            "mseed": p["mseed"], "mode": p["mode"], "bseed": p["bseed"],
            "cluster": p["cluster"], "cluster_long": p["cluster_long"],
            "desc": p["desc"],
        })

    # index csv
    csv_path = os.path.join(OUT_DIR, "cases_index.csv")
    with open(csv_path, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)

    # meson.build — list all 100 case files (meson has no glob; regenerate this
    # file whenever the case set changes). The case files live in this dir.
    meson_lines = [
        "# AUTO-GENERATED by scripts/generate_sdc_fuzz_cases.py — do not edit.",
        "# Lists the 100 core-179 SDC reproducer test cases (aarch64 only).",
        "# Each case links the Eigen machine code (SimplicialCholesky factorize,",
        "# the verified core-179 SDC trigger sequence, report §11.2).",
        "# SPDX-License-Identifier: Apache-2.0",
        "# Copyright 2025 Intel Corporation.",
        "",
        "if host_machine.cpu_family() == 'aarch64'",
        "    sdc_fuzz_cases = files(",
    ]
    for r in rows:
        meson_lines.append(f"        '{r['file']}',")
    meson_lines += [
        "    )",
        "    sdc_fuzz_lib = static_library(",
        "        'tests_sdc_fuzzing',",
        "        sdc_fuzz_cases,",
        "        build_by_default: false,",
        "        include_directories: [framework_incdir],",
        "        dependencies: [eigen3_dep],",
        "        cpp_args: [",
        "            debug_c_flags,",
        "            default_cpp_flags,",
        "            default_cpp_warn,",
        "            march_generic_flags,",
        "            '-march=armv8.1-a+crc+crypto',",
        "        ],",
        "    )",
        "    sandstone_tests += [sdc_fuzz_lib]",
        "endif",
        "",
    ]
    meson_path = os.path.join(OUT_DIR, "meson.build")
    with open(meson_path, "w") as f:
        f.write("\n".join(meson_lines))

    # cluster summary
    from collections import Counter
    c = Counter(r["cluster"] for r in rows)
    mode_c = Counter(r["mode"] for r in rows)
    print(f"Generated {len(rows)} cases in {OUT_DIR}")
    print(f"Clusters: {dict(c)}")
    print(f"Modes: 0(compute-both)={mode_c.get(0,0)}, 1(numeric-only)={mode_c.get(1,0)}")
    print(f"Index: {csv_path}")
    print(f"Meson: {meson_path}")
    print("Files:")
    for r in rows[:3]:
        print(f"  {r['file']}  {r['desc'][:70]}...")
    print(f"  ... ({len(rows)} total)")

if __name__ == "__main__":
    main()
